# -*- coding: utf-8 -*-


batch_size: 128
learning_rate: 0.001
num_episodes: 200000
mem_capacity: 10000
train_steps: 1000000
warmup: 10
save_freq: 1000
    
gamma: 0.99
max_steps_per_episode: 30
target_update_freq: 100
max_queue_length: 50000
    
max_epsilon: 1
min_epsilon: 0.05
decay_epsilon: 250